// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "localhost:8080",
            "email": "sagarsingh@polarisgrids.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get-all-users": {
            "get": {
                "description": "Get All Users Details From the DataBase",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users Data"
                ],
                "summary": "Get all users API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ResponseData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "error": {},
                        "result": {
                            "type": "object",
                            "properties": {
                                "results": {
                                    "type": "array",
                                    "items": {}
                                }
                            }
                        }
                    }
                },
                "responseCode": {
                    "type": "integer"
                },
                "responseDetail": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gin Tutorial API",
	Description:      "ginTut Api Docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
